
services:
  db:
    image: mariadb:10.11
    container_name: rarayvision-db
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT:-}
      MARIADB_DATABASE: ${DB_NAME:-}
      MARIADB_USER: ${DB_USER:-}
      MARIADB_PASSWORD: ${DB_PASS:-}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - raray-network

  backend:
    build: 
      context: .
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
        HTTP_PROXY: ${HTTP_PROXY:-}
        APT_PROXY: ${APT_PROXY:-}
        NO_PROXY: ${NO_PROXY:-}
    container_name: rarayvision-backend
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - raray-network
    volumes:
      - ./backend/uploads:/app/backend/uploads
      - ./backend/models:/app/backend/models
      - ./backend/ml_models:/root/.insightface/models/
    # Ports are omitted because frontend nginx proxies requests

  frontend:
    build:
      context: ./frontend
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
        HTTP_PROXY: ${HTTP_PROXY:-}
        APT_PROXY: ${APT_PROXY:-}
        NO_PROXY: ${no_proxy:-}
        no_proxy: ${no_proxy:-}
        VITE_API_BASE_URL: ${VITE_API_BASE_URL:-http://127.0.0.1:5000}
    container_name: rarayvision-frontend
    restart: unless-stopped
    environment:
      - http_proxy=${HTTP_PROXY:-}
      - https_proxy=${HTTP_PROXY:-}
      - no_proxy=${no_proxy:-}
    depends_on:
      - backend
      - db
    networks:
      - raray-network
    ports:
      - "8001:80"

volumes:
  db_data:

networks:
  raray-network:
    driver: bridge